[ci skip] More refactoring... will take a while

diff --git a/tool/dev/check-env b/tool/dev/check-env
--- a/tool/dev/check-env
+++ b/tool/dev/check-env
@@ -2,17 +2,14 @@
 
 # Checks the environment in which the tool scripts can run properly
 
-if ! [ -f ./.travis.yml ]; then
-  >&2 echo 'ERROR: All tool scripts need to be executed from the bibliograph root directory'
-  exit 1
-fi
-
-if ! [ -f ./.env ]; then
-  >&2 echo 'ERROR: .env file is missing in the root directory - please rename .env.dist to .env'
-  exit 1
-fi
+[ "$(type -t mysql_root)" == "function" ] || source tool/lib/functions.sh
 
 if ! type docker > /dev/null; then
   echo "ERROR: You need docker for the development environment"
+  exit 1
+fi
+
+if ! [ -f "./package.json" ]; then
+  >&2 echo 'ERROR: All tool scripts need to be executed from the bibliograph root directory'
   exit 1
 fi
diff --git a/tool/dev/check-mysql b/tool/dev/check-mysql
--- a/tool/dev/check-mysql
+++ b/tool/dev/check-mysql
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
 
-tool/dev/check-env && source ./.env
+source tool/dev/check-env
+source tool/dev/check-envvars
 tool/dev/servers-start
-source tool/lib/functions.sh
 
 # Exit on first error
 set -o errexit
 
-echo -n ">>> Checking mysql root connection from host ..."
-tool/dev/mysql-client -uroot -p$DB_ROOT_PASSWORD --version > /dev/null || (echo "${COLOR_RED}Failed." && exit 1)
-echo " ${COLOR_GREEN}√${STYLE_RESET}"
+echo -n ">>> Checking mysql user '$DB_USER' connection from host to database ... "
+output=$(tool/dev/mysql-client -u$DB_USER -p$DB_PASSWORD --version)
+if [ $? -ne 0 ]; then echo "$CROSSMARK"; log_error $output; exit 1; fi
+echo "${CHECKMARK}"
+echo "$output"
 
-echo -n ">>> Checking mysql root connection from php container ..."
-tool/dev/php -r \
-  "if(!@mysqli_connect('$DB_HOST', 'root', '$DB_ROOT_PASSWORD')) echo 'Error: Unable to connect to MySQL:'.mysqli_connect_error().PHP_EOL;" \
-  || exit 1
-echo " ${COLOR_GREEN}√${STYLE_RESET}"
+echo -n ">>> Checking mysql user '$DB_USER' connection from php container ... "
+tool/dev/php -r "if(!@mysqli_connect('$DB_HOST', '$DB_USER', '$DB_PASSWORD')){echo '$CROSSMARK' . PHP_EOL .'${COLOR_RED}Error: Unable to connect to MySQL: '.mysqli_connect_error().PHP_EOL.'${STYLE_RESET}';exit(1);}"
+echo "${CHECKMARK}"
