fixes

diff --git a/tool/dev/install-dev-env b/tool/dev/install-dev-env
--- a/tool/dev/install-dev-env
+++ b/tool/dev/install-dev-env
@@ -12,33 +12,40 @@ docker pull mariadb
 
 echo ">>> Installing git in http-server container"
 tool/dev/http-server start
-docker exec -it http-server apt-get update
-docker exec -it http-server apt-get install git
 
-echo " >>> Installing composer ..."
-EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
-php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
-
-if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
-then
-    >&2 echo 'ERROR: Invalid installer signature'
-    rm src/server/composer-setup.php
-    exit 1
+# until the docker image is updated
+docker exec -it http-server git version 2&> /dev/null
+if [ $? -ne 0 ]; then
+ echo "Installing git in container, please wait... "
+ docker exec -it http-server apt update
+ docker exec -it http-server apt install git -y
 fi
 
-php src/server/composer-setup.php --install-dir=./src/lib #--quiet
-RESULT=$?
-rm src/server/composer-setup.php
-if [ $RESULT -eq 1 ]; then
-  >&2 echo "ERROR: Failed to setup composer ..."
-  exit 1
+if ! [ -f src/lib/composer.phar ] ; then
+  echo " >>> Installing composer ..."
+  EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+  tool/dev/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+  ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+  if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+  then
+      >&2 echo 'ERROR: Invalid installer signature'
+      rm src/server/composer-setup.php
+      exit 1
+  fi
+
+  tool/dev/php composer-setup.php --install-dir=src/lib #--quiet
+  RESULT=$?
+  rm src/server/composer-setup.php
+  if [ $RESULT -eq 1 ]; then
+    >&2 echo "ERROR: Failed to setup composer ..."
+    exit 1
+  fi
 fi
 
 # Install needed GitHub repos
 echo " >>> Installing github repositories..."
 
-cd /src/lib
 declare -a arr=(
   "cboulanger/yii2-jsonrpc"
   "cboulanger/raptor-client"
@@ -48,19 +55,19 @@ declare -a arr=(
 )
 for repo in "${arr[@]}"
 do
-  dir=$(basename $repo)
+  dir=./src/lib/$(basename $repo)
   if [ -d "$dir" ]; then
     echo "Updating $repo..."
-    cd $dir
+    pushd $dir > /dev/null || exit 1
     git pull
     [[ -f package.json ]] && npm install
-    cd ..
+    popd > /dev/null
   else
     echo "Checking out $repo..."
     uri="https://github.com/$repo.git"
-    git clone $uri --depth 1
-    cd $dir
+    git clone $uri --depth 1 $dir
+    pushd $dir > /dev/null || exit 1
     [[ -f package.json ]] && npm install --only=prod && npm audit fix
-    cd ..
+    popd > /dev/null
   fi
 done
